package suggestions

import (
	"time"

	"github.com/prometheus/client_golang/prometheus"
)

var (
	rulesEvaluatedTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "dealsignal_suggestion_rules_evaluated_total",
			Help: "Total number of expression rule evaluations by rule_id and match result.",
		},
		[]string{"rule_id", "matched"},
	)

	rulesBucketSkippedTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "dealsignal_suggestion_rules_bucket_skips_total",
			Help: "Total number of expression rules skipped due to A/B bucketing.",
		},
		[]string{"rule_id", "bucket_key"},
	)

	rulesShadowMatchedTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "dealsignal_suggestion_rules_shadow_matched_total",
			Help: "Total number of shadow-mode rule hits (not emitted as suggestions).",
		},
		[]string{"rule_id"},
	)

	suggestionGenerationDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "dealsignal_suggestion_generation_duration_seconds",
			Help:    "Suggestion generation latency in seconds.",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"workspace_id"},
	)

	suggestionsGeneratedTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "dealsignal_suggestions_generated_total",
			Help: "Total number of suggestions generated by type and subtype.",
		},
		[]string{"type", "subtype"},
	)

	suggestionGenerationErrors = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "dealsignal_suggestion_generation_errors_total",
			Help: "Total number of suggestion generation errors by step.",
		},
		[]string{"step"},
	)
)

func init() {
	_ = prometheus.Register(rulesEvaluatedTotal)
	_ = prometheus.Register(rulesBucketSkippedTotal)
	_ = prometheus.Register(rulesShadowMatchedTotal)
	_ = prometheus.Register(suggestionGenerationDuration)
	_ = prometheus.Register(suggestionsGeneratedTotal)
	_ = prometheus.Register(suggestionGenerationErrors)
}

func recordRuleEvaluated(ruleID string, matched bool) {
	m := "false"
	if matched {
		m = "true"
	}
	rulesEvaluatedTotal.WithLabelValues(ruleID, m).Inc()
}

func recordRuleBucketSkipped(ruleID, bucketKey string) {
	rulesBucketSkippedTotal.WithLabelValues(ruleID, bucketKey).Inc()
}

func recordRuleShadowMatched(ruleID string) {
	rulesShadowMatchedTotal.WithLabelValues(ruleID).Inc()
}

func observeSuggestionGenerationDuration(workspaceID string, start time.Time) {
	suggestionGenerationDuration.WithLabelValues(workspaceID).Observe(time.Since(start).Seconds())
}

func recordSuggestionGenerated(typ, subtype string) {
	suggestionsGeneratedTotal.WithLabelValues(typ, subtype).Inc()
}

func recordSuggestionGenerationError(step string) {
	suggestionGenerationErrors.WithLabelValues(step).Inc()
}
