// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AssistantMessage struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	Role      string
	Content   string
	Evidence  []byte
	CreatedAt pgtype.Timestamptz
}

type AssistantSession struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Title       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Chunk struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	WorkspaceID  pgtype.UUID
	PageID       pgtype.UUID
	Text         string
	Bbox         []byte
	Embedding    pgvector.Vector
	SearchVector interface{}
}

type Document struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	CreatedBy   pgtype.UUID
	Title       string
	SourceType  string
	Status      string
	StorageKey  string
	PageCount   pgtype.Int4
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type IngestionJob struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	WorkspaceID  pgtype.UUID
	DocumentID   pgtype.UUID
	Status       string
	Attempts     pgtype.Int4
	ErrorMessage pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Page struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	WorkspaceID    pgtype.UUID
	DocumentID     pgtype.UUID
	PageNumber     int32
	ImageObjectKey pgtype.Text
	Width          pgtype.Int4
	Height         pgtype.Int4
	CreatedAt      pgtype.Timestamptz
}

type Tenant struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type Workspace struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	Name       string
	Slug       string
	BrandColor pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	JoinedAt    pgtype.Timestamptz
}
