// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AccessLog struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	WorkspaceID  pgtype.UUID
	LinkID       pgtype.UUID
	VisitorID    pgtype.Text
	VisitorEmail pgtype.Text
	EventType    string
	Ip           *netip.Addr
	UserAgent    pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type ActionItem struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	SignalID    pgtype.UUID
	Title       string
	Impact      string
	DueAt       pgtype.Timestamptz
	Status      string
	ActionType  string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type AssistantMessage struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	Role      string
	Content   string
	Evidence  []byte
	CreatedAt pgtype.Timestamptz
}

type AssistantSession struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	LinkID      pgtype.UUID
	DocumentID  pgtype.UUID
	Title       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Chunk struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	WorkspaceID    pgtype.UUID
	PageID         pgtype.UUID
	Text           string
	Bbox           []byte
	Embedding      pgvector.Vector
	SearchVector   interface{}
	DocumentID     pgtype.UUID
	ChunkIndex     pgtype.Int4
	NormalizedText pgtype.Text
	ChunkType      pgtype.Text
}

type ChunkBox struct {
	ID              pgtype.UUID
	ChunkID         pgtype.UUID
	DocumentID      pgtype.UUID
	PageNumber      int32
	CoordinateSpace string
	X               float64
	Y               float64
	W               float64
	H               float64
	Source          string
	Confidence      float64
	CreatedAt       pgtype.Timestamptz
}

type Contact struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	Email       pgtype.Text
	Name        pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type Deal struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	ContactID   pgtype.UUID
	Name        string
	Stage       pgtype.Text
	Amount      pgtype.Numeric
	Currency    pgtype.Text
	Status      pgtype.Text
	CloseDate   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type DealRoom struct {
	ID               pgtype.UUID
	TenantID         pgtype.UUID
	WorkspaceID      pgtype.UUID
	Slug             string
	Name             string
	Description      pgtype.Text
	TemplateType     pgtype.Text
	Settings         []byte
	RequiresNda      bool
	RequiresApproval bool
	Status           string
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type DealRoomDocument struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	RoomID      pgtype.UUID
	DocumentID  pgtype.UUID
	FolderPath  string
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
}

type Document struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	CreatedBy   pgtype.UUID
	Title       string
	SourceType  string
	Status      string
	StorageKey  string
	PageCount   pgtype.Int4
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	FileSize    pgtype.Int8
	Category    string
}

type HubspotSyncJob struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	Status       string
	RecordType   string
	RecordID     pgtype.UUID
	Direction    string
	Attempts     int32
	ErrorMessage pgtype.Text
	Payload      []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type IngestionJob struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	WorkspaceID  pgtype.UUID
	DocumentID   pgtype.UUID
	Status       string
	Attempts     pgtype.Int4
	ErrorMessage pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type IntegrationMapping struct {
	ID              pgtype.UUID
	WorkspaceID     pgtype.UUID
	Provider        string
	LocalRecordType string
	LocalID         pgtype.UUID
	ExternalID      string
	ExternalUrl     pgtype.Text
	Metadata        []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type IntegrationSyncLog struct {
	ID           pgtype.UUID
	WorkspaceID  pgtype.UUID
	Provider     string
	Direction    string
	RecordType   string
	ExternalID   pgtype.Text
	Status       string
	Payload      []byte
	ErrorMessage pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type IntegrationToken struct {
	WorkspaceID  pgtype.UUID
	Provider     string
	AccessToken  string
	RefreshToken pgtype.Text
	ExpiresAt    pgtype.Timestamptz
	Scope        pgtype.Text
	ExternalID   pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Link struct {
	ID                       pgtype.UUID
	TenantID                 pgtype.UUID
	WorkspaceID              pgtype.UUID
	DocumentID               pgtype.UUID
	PublicToken              string
	Name                     pgtype.Text
	PermissionType           string
	AllowedEmails            []byte
	AllowedDomains           []byte
	PasswordHash             pgtype.Text
	ExpiresAt                pgtype.Timestamptz
	MaxAccessCount           pgtype.Int4
	AccessCount              int32
	DownloadEnabled          bool
	WatermarkEnabled         bool
	Status                   string
	CreatedBy                pgtype.UUID
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	RequireEmail             bool
	RequirePassword          bool
	RequireNda               bool
	RequireEmailVerification bool
	AiCopilotEnabled         bool
}

type LinkContact struct {
	ID         pgtype.UUID
	LinkID     pgtype.UUID
	ContactID  pgtype.UUID
	AccessCode string
	CodeSentAt pgtype.Timestamptz
	UsedAt     pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type LinkDocument struct {
	ID         pgtype.UUID
	LinkID     pgtype.UUID
	DocumentID pgtype.UUID
	SortOrder  int32
	CreatedAt  pgtype.Timestamptz
}

type LinkNdaAgreement struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	LinkID      pgtype.UUID
	VisitorID   pgtype.Text
	Email       pgtype.Text
	Ip          *netip.Addr
	UserAgent   pgtype.Text
	NdaAgreed   bool
	SignedAt    pgtype.Timestamptz
}

type Notification struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Channel     string
	Subject     string
	Body        string
	Status      string
	Attempts    int32
	LastError   pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type NotificationSetting struct {
	WorkspaceID         pgtype.UUID
	EmailEnabled        bool
	SlackWebhookUrl     pgtype.Text
	SlackConnected      bool
	HubspotConnected    bool
	SalesforceConnected bool
	UpdatedAt           pgtype.Timestamptz
}

type OauthState struct {
	State       string
	WorkspaceID pgtype.UUID
	Provider    string
	ExpiresAt   pgtype.Timestamptz
}

type Page struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	WorkspaceID    pgtype.UUID
	DocumentID     pgtype.UUID
	PageNumber     int32
	ImageObjectKey pgtype.Text
	Width          pgtype.Int4
	Height         pgtype.Int4
	CreatedAt      pgtype.Timestamptz
	FileSize       pgtype.Int8
}

type PageView struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	WorkspaceID     pgtype.UUID
	LinkID          pgtype.UUID
	VisitorID       pgtype.Text
	PageNumber      int32
	DurationSeconds int32
	ScrollDepth     pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
}

type RoomAccessRequest struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	RoomID      pgtype.UUID
	Email       string
	Reason      pgtype.Text
	Status      string
	ReviewedBy  pgtype.UUID
	ReviewedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RoomMember struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	RoomID      pgtype.UUID
	Email       string
	UserID      pgtype.UUID
	Role        string
	NdaStatus   string
	NdaSignedAt pgtype.Timestamptz
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RoomMemberFolderPermission struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	RoomID      pgtype.UUID
	Email       string
	FolderPath  string
	Permission  string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RoomNdaAgreement struct {
	ID        pgtype.UUID
	RoomID    pgtype.UUID
	Email     string
	Ip        *netip.Addr
	UserAgent pgtype.Text
	AgreedAt  pgtype.Timestamptz
}

type Signal struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	WorkspaceID  pgtype.UUID
	SuggestionID pgtype.UUID
	Type         string
	Title        string
	Description  string
	Explanation  string
	Suggestion   string
	DocumentID   pgtype.UUID
	ContactID    pgtype.UUID
	LinkID       pgtype.UUID
	Priority     string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Suggestion struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	ContactID   pgtype.UUID
	LinkID      pgtype.UUID
	DocumentID  pgtype.UUID
	Type        string
	Reason      string
	Action      string
	Dismissed   bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Tenant struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	Slug      pgtype.Text
}

type TenantDomain struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	Domain       string
	DomainType   string
	IsPrimary    bool
	SslStatus    string
	SslExpiresAt pgtype.Timestamptz
	VerifiedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Email         string
	PasswordHash  string
	CreatedAt     pgtype.Timestamptz
	EmailVerified bool
}

type Workspace struct {
	ID                     pgtype.UUID
	TenantID               pgtype.UUID
	Name                   string
	Slug                   string
	BrandColor             pgtype.Text
	CreatedAt              pgtype.Timestamptz
	ForceEmailVerification bool
	WatermarkDownloads     bool
	TwoFactorEnabled       bool
}

type WorkspaceInvitation struct {
	Token       pgtype.UUID
	WorkspaceID pgtype.UUID
	Email       string
	Role        string
	ExpiresAt   pgtype.Timestamptz
	UsedAt      pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	JoinedAt    pgtype.Timestamptz
}
