// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AccessLog struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	WorkspaceID  pgtype.UUID
	LinkID       pgtype.UUID
	VisitorID    pgtype.Text
	VisitorEmail pgtype.Text
	EventType    string
	Ip           *netip.Addr
	UserAgent    pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type AssistantMessage struct {
	ID        pgtype.UUID
	SessionID pgtype.UUID
	Role      string
	Content   string
	Evidence  []byte
	CreatedAt pgtype.Timestamptz
}

type AssistantSession struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Title       pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Chunk struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	WorkspaceID  pgtype.UUID
	PageID       pgtype.UUID
	Text         string
	Bbox         []byte
	Embedding    pgvector.Vector
	SearchVector interface{}
}

type DealRoom struct {
	ID               pgtype.UUID
	TenantID         pgtype.UUID
	WorkspaceID      pgtype.UUID
	Slug             string
	Name             string
	Description      pgtype.Text
	TemplateType     pgtype.Text
	Settings         []byte
	RequiresNda      bool
	RequiresApproval bool
	Status           string
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type DealRoomDocument struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	RoomID      pgtype.UUID
	DocumentID  pgtype.UUID
	FolderPath  string
	SortOrder   int32
	CreatedAt   pgtype.Timestamptz
}

type Document struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	CreatedBy   pgtype.UUID
	Title       string
	SourceType  string
	Status      string
	StorageKey  string
	PageCount   pgtype.Int4
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type IngestionJob struct {
	ID           pgtype.UUID
	TenantID     pgtype.UUID
	WorkspaceID  pgtype.UUID
	DocumentID   pgtype.UUID
	Status       string
	Attempts     pgtype.Int4
	ErrorMessage pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Link struct {
	ID               pgtype.UUID
	TenantID         pgtype.UUID
	WorkspaceID      pgtype.UUID
	DocumentID       pgtype.UUID
	PublicToken      string
	Name             pgtype.Text
	PermissionType   string
	AllowedEmails    []byte
	AllowedDomains   []byte
	PasswordHash     pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	MaxAccessCount   pgtype.Int4
	AccessCount      int32
	DownloadEnabled  bool
	WatermarkEnabled bool
	Status           string
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Page struct {
	ID             pgtype.UUID
	TenantID       pgtype.UUID
	WorkspaceID    pgtype.UUID
	DocumentID     pgtype.UUID
	PageNumber     int32
	ImageObjectKey pgtype.Text
	Width          pgtype.Int4
	Height         pgtype.Int4
	CreatedAt      pgtype.Timestamptz
}

type PageView struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	WorkspaceID     pgtype.UUID
	LinkID          pgtype.UUID
	VisitorID       pgtype.Text
	PageNumber      int32
	DurationSeconds int32
	ScrollDepth     pgtype.Numeric
	CreatedAt       pgtype.Timestamptz
}

type RoomAccessRequest struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	RoomID      pgtype.UUID
	Email       string
	Reason      pgtype.Text
	Status      string
	ReviewedBy  pgtype.UUID
	ReviewedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RoomMember struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	RoomID      pgtype.UUID
	Email       string
	UserID      pgtype.UUID
	Role        string
	NdaStatus   string
	NdaSignedAt pgtype.Timestamptz
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RoomMemberFolderPermission struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	RoomID      pgtype.UUID
	Email       string
	FolderPath  string
	Permission  string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type RoomNdaAgreement struct {
	ID        pgtype.UUID
	RoomID    pgtype.UUID
	Email     string
	Ip        *netip.Addr
	UserAgent pgtype.Text
	AgreedAt  pgtype.Timestamptz
}

type Tenant struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}

type Workspace struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	Name       string
	Slug       string
	BrandColor pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type WorkspaceMember struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
	JoinedAt    pgtype.Timestamptz
}
