// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :one
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING workspace_id, user_id, role, joined_at
`

type AddWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
	Role        string
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createAccessLog = `-- name: CreateAccessLog :exec
INSERT INTO access_logs (tenant_id, workspace_id, link_id, visitor_id, visitor_email, event_type, ip, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAccessLogParams struct {
	TenantID     pgtype.UUID
	WorkspaceID  pgtype.UUID
	LinkID       pgtype.UUID
	VisitorID    pgtype.Text
	VisitorEmail pgtype.Text
	EventType    string
	Ip           *netip.Addr
	UserAgent    pgtype.Text
}

func (q *Queries) CreateAccessLog(ctx context.Context, arg CreateAccessLogParams) error {
	_, err := q.db.Exec(ctx, createAccessLog,
		arg.TenantID,
		arg.WorkspaceID,
		arg.LinkID,
		arg.VisitorID,
		arg.VisitorEmail,
		arg.EventType,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const createChunk = `-- name: CreateChunk :exec
INSERT INTO chunks (tenant_id, workspace_id, page_id, text, bbox)
VALUES ($1, $2, $3, $4, $5)
`

type CreateChunkParams struct {
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	PageID      pgtype.UUID
	Text        string
	Bbox        []byte
}

func (q *Queries) CreateChunk(ctx context.Context, arg CreateChunkParams) error {
	_, err := q.db.Exec(ctx, createChunk,
		arg.TenantID,
		arg.WorkspaceID,
		arg.PageID,
		arg.Text,
		arg.Bbox,
	)
	return err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    id, tenant_id, workspace_id, created_by, title, source_type, status, storage_key
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, workspace_id, created_by, title, source_type, status, storage_key, page_count, created_at, updated_at, deleted_at
`

type CreateDocumentParams struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	CreatedBy   pgtype.UUID
	Title       string
	SourceType  string
	Status      string
	StorageKey  string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.TenantID,
		arg.WorkspaceID,
		arg.CreatedBy,
		arg.Title,
		arg.SourceType,
		arg.Status,
		arg.StorageKey,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Title,
		&i.SourceType,
		&i.Status,
		&i.StorageKey,
		&i.PageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createIngestionJob = `-- name: CreateIngestionJob :one
INSERT INTO ingestion_jobs (tenant_id, workspace_id, document_id, status)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, workspace_id, document_id, status, attempts, error_message, created_at, updated_at
`

type CreateIngestionJobParams struct {
	TenantID    pgtype.UUID
	WorkspaceID pgtype.UUID
	DocumentID  pgtype.UUID
	Status      string
}

func (q *Queries) CreateIngestionJob(ctx context.Context, arg CreateIngestionJobParams) (IngestionJob, error) {
	row := q.db.QueryRow(ctx, createIngestionJob,
		arg.TenantID,
		arg.WorkspaceID,
		arg.DocumentID,
		arg.Status,
	)
	var i IngestionJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkspaceID,
		&i.DocumentID,
		&i.Status,
		&i.Attempts,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO links (
    tenant_id, workspace_id, document_id, public_token, name, permission_type,
    allowed_emails, allowed_domains, password_hash, expires_at, max_access_count,
    download_enabled, watermark_enabled, status, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, tenant_id, workspace_id, document_id, public_token, name, permission_type,
          allowed_emails, allowed_domains, password_hash, expires_at, max_access_count,
          access_count, download_enabled, watermark_enabled, status, created_by, created_at, updated_at
`

type CreateLinkParams struct {
	TenantID         pgtype.UUID
	WorkspaceID      pgtype.UUID
	DocumentID       pgtype.UUID
	PublicToken      string
	Name             pgtype.Text
	PermissionType   string
	AllowedEmails    []byte
	AllowedDomains   []byte
	PasswordHash     pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	MaxAccessCount   pgtype.Int4
	DownloadEnabled  bool
	WatermarkEnabled bool
	Status           string
	CreatedBy        pgtype.UUID
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.TenantID,
		arg.WorkspaceID,
		arg.DocumentID,
		arg.PublicToken,
		arg.Name,
		arg.PermissionType,
		arg.AllowedEmails,
		arg.AllowedDomains,
		arg.PasswordHash,
		arg.ExpiresAt,
		arg.MaxAccessCount,
		arg.DownloadEnabled,
		arg.WatermarkEnabled,
		arg.Status,
		arg.CreatedBy,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkspaceID,
		&i.DocumentID,
		&i.PublicToken,
		&i.Name,
		&i.PermissionType,
		&i.AllowedEmails,
		&i.AllowedDomains,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.MaxAccessCount,
		&i.AccessCount,
		&i.DownloadEnabled,
		&i.WatermarkEnabled,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPage = `-- name: CreatePage :one
INSERT INTO pages (tenant_id, workspace_id, document_id, page_number, image_object_key, width, height)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, workspace_id, document_id, page_number, image_object_key, width, height, created_at
`

type CreatePageParams struct {
	TenantID       pgtype.UUID
	WorkspaceID    pgtype.UUID
	DocumentID     pgtype.UUID
	PageNumber     int32
	ImageObjectKey pgtype.Text
	Width          pgtype.Int4
	Height         pgtype.Int4
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.TenantID,
		arg.WorkspaceID,
		arg.DocumentID,
		arg.PageNumber,
		arg.ImageObjectKey,
		arg.Width,
		arg.Height,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkspaceID,
		&i.DocumentID,
		&i.PageNumber,
		&i.ImageObjectKey,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const createPageView = `-- name: CreatePageView :exec
INSERT INTO page_views (tenant_id, workspace_id, link_id, visitor_id, page_number, duration_seconds, scroll_depth)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePageViewParams struct {
	TenantID        pgtype.UUID
	WorkspaceID     pgtype.UUID
	LinkID          pgtype.UUID
	VisitorID       pgtype.Text
	PageNumber      int32
	DurationSeconds int32
	ScrollDepth     pgtype.Numeric
}

func (q *Queries) CreatePageView(ctx context.Context, arg CreatePageViewParams) error {
	_, err := q.db.Exec(ctx, createPageView,
		arg.TenantID,
		arg.WorkspaceID,
		arg.LinkID,
		arg.VisitorID,
		arg.PageNumber,
		arg.DurationSeconds,
		arg.ScrollDepth,
	)
	return err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateTenant(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, name)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, created_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (tenant_id, name, slug, brand_color)
VALUES ($1, $2, $3, $4) RETURNING id, tenant_id, name, slug, brand_color, created_at
`

type CreateWorkspaceParams struct {
	TenantID   pgtype.UUID
	Name       string
	Slug       string
	BrandColor pgtype.Text
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.TenantID,
		arg.Name,
		arg.Slug,
		arg.BrandColor,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.BrandColor,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, tenant_id, workspace_id, created_by, title, source_type, status, storage_key, page_count, created_at, updated_at, deleted_at
FROM documents
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetDocumentByIDParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) GetDocumentByID(ctx context.Context, arg GetDocumentByIDParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, arg.ID, arg.WorkspaceID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Title,
		&i.SourceType,
		&i.Status,
		&i.StorageKey,
		&i.PageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIngestionJobByDocument = `-- name: GetIngestionJobByDocument :one
SELECT id, tenant_id, workspace_id, document_id, status, attempts, error_message, created_at, updated_at
FROM ingestion_jobs
WHERE document_id = $1
LIMIT 1
`

func (q *Queries) GetIngestionJobByDocument(ctx context.Context, documentID pgtype.UUID) (IngestionJob, error) {
	row := q.db.QueryRow(ctx, getIngestionJobByDocument, documentID)
	var i IngestionJob
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkspaceID,
		&i.DocumentID,
		&i.Status,
		&i.Attempts,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkAccessMetrics = `-- name: GetLinkAccessMetrics :one
SELECT
    COUNT(*) FILTER (WHERE event_type = 'link_opened') AS opens,
    COUNT(DISTINCT visitor_id) FILTER (WHERE event_type = 'link_opened') AS unique_visitors,
    COUNT(*) FILTER (WHERE event_type = 'download_attempted') AS downloads
FROM access_logs
WHERE link_id = $1
`

type GetLinkAccessMetricsRow struct {
	Opens          int64
	UniqueVisitors int64
	Downloads      int64
}

func (q *Queries) GetLinkAccessMetrics(ctx context.Context, linkID pgtype.UUID) (GetLinkAccessMetricsRow, error) {
	row := q.db.QueryRow(ctx, getLinkAccessMetrics, linkID)
	var i GetLinkAccessMetricsRow
	err := row.Scan(&i.Opens, &i.UniqueVisitors, &i.Downloads)
	return i, err
}

const getLinkBounceCount = `-- name: GetLinkBounceCount :one
SELECT COUNT(*) AS bounce_count
FROM access_logs a
WHERE a.link_id = $1
  AND a.event_type = 'link_opened'
  AND a.visitor_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM page_views p
      WHERE p.link_id = $1 AND p.visitor_id = a.visitor_id
  )
`

func (q *Queries) GetLinkBounceCount(ctx context.Context, linkID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getLinkBounceCount, linkID)
	var bounce_count int64
	err := row.Scan(&bounce_count)
	return bounce_count, err
}

const getLinkByIDAndWorkspace = `-- name: GetLinkByIDAndWorkspace :one
SELECT id, tenant_id, workspace_id, document_id, public_token, name, permission_type,
       allowed_emails, allowed_domains, password_hash, expires_at, max_access_count,
       access_count, download_enabled, watermark_enabled, status, created_by, created_at, updated_at
FROM links
WHERE id = $1 AND workspace_id = $2
LIMIT 1
`

type GetLinkByIDAndWorkspaceParams struct {
	ID          pgtype.UUID
	WorkspaceID pgtype.UUID
}

func (q *Queries) GetLinkByIDAndWorkspace(ctx context.Context, arg GetLinkByIDAndWorkspaceParams) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByIDAndWorkspace, arg.ID, arg.WorkspaceID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkspaceID,
		&i.DocumentID,
		&i.PublicToken,
		&i.Name,
		&i.PermissionType,
		&i.AllowedEmails,
		&i.AllowedDomains,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.MaxAccessCount,
		&i.AccessCount,
		&i.DownloadEnabled,
		&i.WatermarkEnabled,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkByPublicToken = `-- name: GetLinkByPublicToken :one
SELECT id, tenant_id, workspace_id, document_id, public_token, name, permission_type,
       allowed_emails, allowed_domains, password_hash, expires_at, max_access_count,
       access_count, download_enabled, watermark_enabled, status, created_by, created_at, updated_at
FROM links
WHERE public_token = $1 AND status = 'active'
LIMIT 1
`

func (q *Queries) GetLinkByPublicToken(ctx context.Context, publicToken string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByPublicToken, publicToken)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkspaceID,
		&i.DocumentID,
		&i.PublicToken,
		&i.Name,
		&i.PermissionType,
		&i.AllowedEmails,
		&i.AllowedDomains,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.MaxAccessCount,
		&i.AccessCount,
		&i.DownloadEnabled,
		&i.WatermarkEnabled,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkPageViewMetrics = `-- name: GetLinkPageViewMetrics :one
SELECT
    COALESCE(AVG(duration_seconds), 0)::float8 AS avg_duration_seconds,
    COUNT(*) FILTER (WHERE duration_seconds >= 3) AS key_page_views,
    COUNT(*) AS total_page_views
FROM page_views
WHERE link_id = $1
`

type GetLinkPageViewMetricsRow struct {
	AvgDurationSeconds float64
	KeyPageViews       int64
	TotalPageViews     int64
}

func (q *Queries) GetLinkPageViewMetrics(ctx context.Context, linkID pgtype.UUID) (GetLinkPageViewMetricsRow, error) {
	row := q.db.QueryRow(ctx, getLinkPageViewMetrics, linkID)
	var i GetLinkPageViewMetricsRow
	err := row.Scan(&i.AvgDurationSeconds, &i.KeyPageViews, &i.TotalPageViews)
	return i, err
}

const getPageByDocumentAndNumber = `-- name: GetPageByDocumentAndNumber :one
SELECT id, tenant_id, workspace_id, document_id, page_number, image_object_key, width, height, created_at
FROM pages
WHERE document_id = $1 AND page_number = $2
LIMIT 1
`

type GetPageByDocumentAndNumberParams struct {
	DocumentID pgtype.UUID
	PageNumber int32
}

func (q *Queries) GetPageByDocumentAndNumber(ctx context.Context, arg GetPageByDocumentAndNumberParams) (Page, error) {
	row := q.db.QueryRow(ctx, getPageByDocumentAndNumber, arg.DocumentID, arg.PageNumber)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkspaceID,
		&i.DocumentID,
		&i.PageNumber,
		&i.ImageObjectKey,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at
FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at
FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT w.id, w.tenant_id, w.name, w.slug, w.brand_color, w.created_at
FROM workspaces w
WHERE w.id = $1 LIMIT 1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id pgtype.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.BrandColor,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT w.id, w.tenant_id, w.name, w.slug, w.brand_color, w.created_at
FROM workspaces w
WHERE w.slug = $1 LIMIT 1
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.BrandColor,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT workspace_id, user_id, role, joined_at
FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2 LIMIT 1
`

type GetWorkspaceMemberParams struct {
	WorkspaceID pgtype.UUID
	UserID      pgtype.UUID
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const incrementLinkAccessCount = `-- name: IncrementLinkAccessCount :exec
UPDATE links
SET access_count = access_count + 1, updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementLinkAccessCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementLinkAccessCount, id)
	return err
}

const listDocumentsByWorkspace = `-- name: ListDocumentsByWorkspace :many
SELECT id, tenant_id, workspace_id, created_by, title, source_type, status, storage_key, page_count, created_at, updated_at, deleted_at
FROM documents
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Document, error) {
	rows, err := q.db.Query(ctx, listDocumentsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Document
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.Title,
			&i.SourceType,
			&i.Status,
			&i.StorageKey,
			&i.PageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksByWorkspace = `-- name: ListLinksByWorkspace :many
SELECT id, tenant_id, workspace_id, document_id, public_token, name, permission_type,
       allowed_emails, allowed_domains, password_hash, expires_at, max_access_count,
       access_count, download_enabled, watermark_enabled, status, created_by, created_at, updated_at
FROM links
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListLinksByWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinksByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkspaceID,
			&i.DocumentID,
			&i.PublicToken,
			&i.Name,
			&i.PermissionType,
			&i.AllowedEmails,
			&i.AllowedDomains,
			&i.PasswordHash,
			&i.ExpiresAt,
			&i.MaxAccessCount,
			&i.AccessCount,
			&i.DownloadEnabled,
			&i.WatermarkEnabled,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagesByDocument = `-- name: ListPagesByDocument :many
SELECT id, tenant_id, workspace_id, document_id, page_number, image_object_key, width, height, created_at
FROM pages
WHERE document_id = $1
ORDER BY page_number
`

func (q *Queries) ListPagesByDocument(ctx context.Context, documentID pgtype.UUID) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPagesByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkspaceID,
			&i.DocumentID,
			&i.PageNumber,
			&i.ImageObjectKey,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT workspace_id, user_id, role, joined_at
FROM workspace_members
WHERE workspace_id = $1
ORDER BY joined_at DESC
`

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID pgtype.UUID) ([]WorkspaceMember, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceMember
	for rows.Next() {
		var i WorkspaceMember
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT w.id, w.tenant_id, w.name, w.slug, w.brand_color, w.created_at, m.role
FROM workspaces w
JOIN workspace_members m ON m.workspace_id = w.id
WHERE m.user_id = $1
ORDER BY w.created_at DESC
`

type ListWorkspacesByUserRow struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	Name       string
	Slug       string
	BrandColor pgtype.Text
	CreatedAt  pgtype.Timestamptz
	Role       string
}

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userID pgtype.UUID) ([]ListWorkspacesByUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspacesByUserRow
	for rows.Next() {
		var i ListWorkspacesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Slug,
			&i.BrandColor,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :exec
UPDATE documents
SET status = $1, page_count = $2, updated_at = now()
WHERE id = $3
`

type UpdateDocumentStatusParams struct {
	Status    string
	PageCount pgtype.Int4
	ID        pgtype.UUID
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDocumentStatus, arg.Status, arg.PageCount, arg.ID)
	return err
}

const updateIngestionJob = `-- name: UpdateIngestionJob :exec
UPDATE ingestion_jobs
SET status = $1, attempts = $2, error_message = $3, updated_at = now()
WHERE id = $4
`

type UpdateIngestionJobParams struct {
	Status       string
	Attempts     pgtype.Int4
	ErrorMessage pgtype.Text
	ID           pgtype.UUID
}

func (q *Queries) UpdateIngestionJob(ctx context.Context, arg UpdateIngestionJobParams) error {
	_, err := q.db.Exec(ctx, updateIngestionJob,
		arg.Status,
		arg.Attempts,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}
